package example.news.entity;

public enum EnumPermission {

    USER_CREATE, USER_READ, USER_UPDATE, USER_DELETE,
    NEWS_CREATE, NEWS_READ, NEWS_UPDATE, NEWS_DELETE,

    GROUP_CREATE, GROUP_READ, GROUP_UPDATE, GROUP_DELETE,

    COMMENT_CREATE, COMMENT_READ, COMMENT_UPDATE, COMMENT_DELETE
}
